**Problem 1**

Import Numpy as np

In [2]:

import numpy as np  


**Problem 2**

Create a 1D array of numbers from 0 to 9.

In [28]:
arr = np.arange(0,10)
print(arr) 

[0 1 2 3 4 5 6 7 8 9]


**Problem 3**

Create a 3×3 numpy array of all True’s.

In [23]:
arr = np.ones((4, 4), dtype=bool)
print(arr)

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


**Problem 4**

Extract all odd numbers from arr.

In [24]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr_odd = arr[arr %2 ==1]
print(arr_odd)

[1 3 5 7 9]


**Problem 5**

Replace all odd numbers in arr with -1.

In [30]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


**Problem 6**

Convert a 1D array to a 2D array with 2 rows.

In [63]:

arr = np.arange(10)
# np.reshape(arr, (3, 3))
print(np.reshape(arr, (2, 5)))

[[0 1 2 3 4]
 [5 6 7 8 9]]


**Problem 7** 

Stack arrays a and b vertically.

In [30]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
c = np.vstack((a, b))
print(a)
print(np.transpose(b))
print(c)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


**Problem 8**

Stack the arrays a and b horizontally.

In [31]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
c = np.hstack((a, b))
print(a)
print(np.transpose(b))
print(c)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


**Problem 9**

Get the common items between a and b.

In [36]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
c = np.intersect1d(a, b)
# d= np.array_equal(a, b)
print(c)


[2 4]


**Problem 10**

From array a remove all items present in array b

In [42]:
a = np.array([1,2,3,4,5,5])
b = np.array([5,6,7,8,9])
c = np.setdiff1d(a ,b)
print(c)

[1 2 3 4]


**Problem 11**

Get the positions where elements of a and b match

In [77]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
# c = np.intersect1d(a, b, return_indices=True)[0]  #matching values
c = np.where(a == b) # matching positions
print(c)

(array([1, 3, 5, 7], dtype=int64),)


**Problem 12** 

Get all items between 5 and 10 from a.

In [79]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
c = a[(a >= 5) &  (a <= 10)]
print(c)

[ 6  9 10]


**Problem 13**

Swap columns 1 and 2 in the array arr.

In [15]:
arr = np.arange(9).reshape(3,3)
print(arr)
arr = np.swapaxes(arr, 0, 1)
print(arr)                  



[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]


**Problem 14**

Swap rows 1 and 2 in the array arr.

In [14]:
arr = np.arange(9).reshape(3,3)
print(arr)

arr[[1, 0]] = arr[[0, 1]]
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[3 4 5]
 [0 1 2]
 [6 7 8]]


**Problem 15**

Reverse the rows of a 2D array arr.

In [11]:
arr = np.arange(9).reshape(3,3)
a = np.flipud(arr)
print(a)


[[6 7 8]
 [3 4 5]
 [0 1 2]]


**Problem 16**

Reverse the columns of a 2D array arr.

In [10]:
arr = np.arange(9).reshape(3,3)
a = arr[:, ::-1]
b = np.fliplr(arr)
print(a)
print(b)

[[2 1 0]
 [5 4 3]
 [8 7 6]]
[[2 1 0]
 [5 4 3]
 [8 7 6]]


**Problem 17**

Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10

In [31]:
a = np.random.uniform(low=5, high=10, size=(5,3))
print(a)


[[6.65972722 7.79557584 7.60409217]
 [8.88297582 7.56397696 6.64255998]
 [5.64754984 9.08005104 6.37339463]
 [7.86037688 8.79446709 5.05979093]
 [5.69061373 8.31256981 7.30723311]]


**Problem 18**

Print or show only 3 decimal places of the numpy array rand_arr.

In [90]:
rand_arr = np.random.rand(3,3)
np.set_printoptions(precision=3)
print(rand_arr)

[[0.728 0.668 0.664]
 [0.708 0.045 0.546]
 [0.941 0.75  0.192]]
